import {$,err,esc} from '../core/utils.js';
import {REPORT_PARTS} from '../core/config.js';
import {getState,setState,persistWorkspace} from '../core/store.js';
import {ensureAuth} from './auth.js';
import {checkDeepSeek} from './deepseek.js';
import {go} from '../core/router.js';
async function callAI(payload){if(!await ensureAuth())throw Error('登入狀態已失效，請重新登入');const s=getState(),r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+s.auth.session.access_token},body:JSON.stringify(payload)}),raw=await r.text();let j={};try{j=JSON.parse(raw)}catch{j={error:raw.slice(0,500)}}if(!r.ok)throw Error(err(j)||`HTTP ${r.status}`);return j}
export function initAI(){$('quickAI').addEventListener('click',quick);$('fullAI').addEventListener('click',full);$('homeAsk').addEventListener('click',()=>{$('question').value=$('homeQ').value;go('report');setTimeout(quick,20)});document.querySelectorAll('[data-vol]').forEach(x=>x.addEventListener('click',()=>go('report')))}
async function quick(){try{$('aiOut').textContent='DeepSeek 分析中…';const s=getState(),j=await callAI({mode:'chat',question:$('question').value||'請綜合解讀目前命盤',context:contextOf(s)});setState({report:j.text||'',reportParts:[j.text||''],reportStatus:{running:false,completed:1,total:1,current:'',chars:(j.text||'').length,sections:1}},{type:'report'});persistWorkspace()}catch(e){$('aiOut').textContent='DeepSeek 呼叫失敗：'+err(e)}}
async function full(){let s=getState();if(!s.chart){go('chart');$('chartOut').textContent='請先生成命盤';return}const parts=[];setState({report:'',reportParts:[],reportStatus:{running:true,completed:0,total:5,current:REPORT_PARTS[0][1],chars:0,sections:0}},{type:'report-start'});for(let i=0;i<REPORT_PARTS.length;i++){const[code,title,target]=REPORT_PARTS[i];updateVolume(i,'生成中…');setState({reportStatus:{...getState().reportStatus,current:title,completed:i}},{type:'report-progress'});try{let j=await callAI({mode:'report_part',part:code,question:$('question').value,context:contextOf(getState()),targetChars:target}),text=(j.text||'').trim();for(let round=1;round<=3&&text.length<target;round++){updateVolume(i,`續寫 ${round} · ${text.length}/${target} 字`);const c=await callAI({mode:'report_continue',part:code,question:$('question').value,context:contextOf(getState()),previousText:text.slice(-12000),currentChars:text.length,targetChars:target,missingChars:target-text.length});const extra=(c.text||'').trim();if(!extra)break;text+='\n\n'+extra}parts.push(`# ${title}\n\n${text||'本卷未返回內容'}`);updateVolume(i,`已生成 · ${text.length.toLocaleString('zh-TW')} 字`)}catch(e){const m=err(e);parts.push(`# ${title}\n\n本卷生成失敗：${m}`);updateVolume(i,'生成失敗 · '+m.slice(0,28))}const joined=parts.join('\n\n'),completed=i+1;setState({report:joined,reportParts:[...parts],reportStatus:{running:completed<5,completed,total:5,current:completed<5?REPORT_PARTS[completed][1]:'',chars:joined.length,sections:completed}},{type:'report-progress'});persistWorkspace();renderReport(getState())}checkDeepSeek()}
function contextOf(s){return{chart:s.chart,selectedYear:s.selectedYear,selectedPalace:s.selectedPalace,visual:s.visual}}
function updateVolume(i,t){const el=$('v'+i);if(el)el.textContent=t}
export function renderAI(s){const rs=s.reportStatus||{};$('progress').style.width=`${Math.min(100,(rs.completed||0)/(rs.total||5)*100)}%`;$('progressText').textContent=rs.running?`正在生成：${rs.current||'詳批'}`:s.report?'詳批已完成':'尚未開始';$('rParts').textContent=`${rs.completed||0} / ${rs.total||5}`;$('rChars').textContent=(s.report||'').length;$('sChars').textContent=(s.report||'').length;$('rSecs').textContent=rs.sections||0;$('sSecs').textContent=rs.sections||0;$('rState').textContent=rs.running?'生成中':s.report?'已完成':'待生成';if(s.report)renderReport(s);else{$('reportView').hidden=true;$('aiBox').hidden=false}}
function renderReport(s){const text=s.report||'',secs=text.split(/(?=^#\s+)/m).filter(Boolean);$('reportView').hidden=false;$('aiBox').hidden=true;$('toc').innerHTML='';$('reportBody').innerHTML='';secs.forEach((sec,i)=>{const lines=sec.trim().split('\n'),title=lines.shift().replace(/^#\s*/,''),id='sec'+i;$('toc').insertAdjacentHTML('beforeend',`<button data-target="${id}">${esc(title)}</button>`);$('reportBody').insertAdjacentHTML('beforeend',`<section id="${id}"><h3>${esc(title)}</h3>${lines.filter(Boolean).map(x=>`<p>${esc(x)}</p>`).join('')}</section>`)});$('toc').querySelectorAll('button').forEach(b=>b.onclick=()=>$(b.dataset.target).scrollIntoView({behavior:'smooth'}));$('aiOut').textContent=text}
