import {SUPABASE_URL,SUPABASE_KEY,SESSION_KEY} from '../core/config.js';
import {$,err} from '../core/utils.js';
import {getState,setState,restoreWorkspace,resetWorkspace} from '../core/store.js';
const headers=token=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})});
export async function authFetch(path,opt={}){const r=await fetch(SUPABASE_URL+path,{...opt,headers:{...headers(opt.token),...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(err(j)||`HTTP ${r.status}`);return j}
function read(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function persist(session){session?localStorage.setItem(SESSION_KEY,JSON.stringify(session)):localStorage.removeItem(SESSION_KEY)}
async function hydrate(session,{restore=false}={}){if(!session?.access_token)throw Error('登入憑證不存在');let next={...session};if(!next.expires_at)next.expires_at=Math.floor(Date.now()/1000)+(next.expires_in||3600);if(next.expires_at<Date.now()/1000+60&&next.refresh_token){const j=await authFetch('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:next.refresh_token})});next={...next,...j,expires_at:Math.floor(Date.now()/1000)+(j.expires_in||3600)}}const user=await authFetch('/auth/v1/user',{token:next.access_token});const prev=getState().auth.user?.id;if(prev&&prev!==user.id)resetWorkspace();next.user=user;persist(next);setState({auth:{session:next,user,status:'authenticated'}},{type:'auth'});if(restore)restoreWorkspace(user.id);return next}
export async function ensureAuth({restore=false}={}){const current=getState().auth;if(current.status==='authenticated'&&current.session?.access_token&&current.user){if(!current.session.expires_at||current.session.expires_at>Date.now()/1000+60)return true}const s=current.session||read();if(!s?.access_token){setState({auth:{session:null,user:null,status:'guest'}},{type:'auth'});return false}try{await hydrate(s,{restore});return true}catch{persist(null);resetWorkspace();setState({auth:{session:null,user:null,status:'guest'}},{type:'auth'});return false}}
export function initAuth(){$('login').addEventListener('click',async()=>{try{$('authMsg').textContent='登入中…';const j=await authFetch('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('pass').value})});resetWorkspace();await hydrate(j,{restore:true});$('authMsg').textContent='登入成功'}catch(e){$('authMsg').textContent='登入失敗：'+err(e)}});$('signup').addEventListener('click',async()=>{try{const email=$('email').value.trim(),password=$('pass').value;if(password.length<8)throw Error('密碼至少 8 碼');$('authMsg').textContent='註冊中…';const j=await authFetch('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})});if(j.access_token){resetWorkspace();await hydrate(j,{restore:true});$('authMsg').textContent='註冊成功，已登入'}else $('authMsg').textContent='帳戶已建立，請直接登入。'}catch(e){$('authMsg').textContent='註冊失敗：'+err(e)}});$('logout').addEventListener('click',()=>{persist(null);resetWorkspace();setState({auth:{session:null,user:null,status:'guest'}},{type:'auth'})});$('pass').addEventListener('keydown',e=>{if(e.key==='Enter')$('login').click()})}
export function renderAuth(state){const on=state.auth.status==='authenticated'&&state.auth.user&&state.auth.session?.access_token;$('auth').hidden=!!on;$('app').hidden=!on;$('who').textContent=on?(state.auth.user.email||'已登入'):'未登入';$('accountEmail').textContent=on?(state.auth.user.email||state.auth.user.id):'—'}
export const authHeaders=()=>headers(getState().auth.session?.access_token);
