import {$,safe,err} from '../core/utils.js';
import {getState,setState,persistWorkspace} from '../core/store.js';
export const GAN='甲乙丙丁戊己庚辛壬癸'.split(''),ZHI='子丑寅卯辰巳午未申酉戌亥'.split('');
export const STEM_ELEMENT={甲:'木',乙:'木',丙:'火',丁:'火',戊:'土',己:'土',庚:'金',辛:'金',壬:'水',癸:'水'};
export const BRANCH_ELEMENT={子:'水',丑:'土',寅:'木',卯:'木',辰:'土',巳:'火',午:'火',未:'土',申:'金',酉:'金',戌:'土',亥:'水'};
const GEN={木:'火',火:'土',土:'金',金:'水',水:'木'},CTL={木:'土',土:'水',水:'火',火:'金',金:'木'};
const yang=x=>GAN.indexOf(x)%2===0;
export function tenGod(day,other){const a=STEM_ELEMENT[day],b=STEM_ELEMENT[other],same=yang(day)===yang(other);if(!a||!b)return'未知';if(a===b)return same?'比肩':'劫財';if(GEN[a]===b)return same?'食神':'傷官';if(CTL[a]===b)return same?'偏財':'正財';if(CTL[b]===a)return same?'七殺':'正官';if(GEN[b]===a)return same?'偏印':'正印';return'未知'}
export function yearGanzhi(y){const i=((y-1984)%60+60)%60;return GAN[i%10]+ZHI[i%12]}
export function monthSequence(y,dayStem){const i=GAN.indexOf(yearGanzhi(y)[0]),first=((i%5)*2+2)%10;return Array.from({length:12},(_,n)=>{const s=GAN[(first+n)%10],b=ZHI[(2+n)%12];return{n:n+1,gz:s+b,tg:tenGod(dayStem,s)}})}
function timeIndex(h){return h===23||h===0?0:Math.floor((h+1)/2)}
function eot(d){const n=(d-new Date(d.getFullYear(),0,0))/864e5,B=2*Math.PI*(n-81)/364;return 9.87*Math.sin(2*B)-7.53*Math.cos(B)-1.5*Math.sin(B)}
function timeline(ec,gender,year){const d=ec.getDay()[0],yun=safe(()=>ec.getYun(gender==='男'?1:0),null),dy=safe(()=>yun?.getDaYun(12),[]).map(x=>({gz:safe(()=>x.getGanZhi()),sy:safe(()=>x.getStartYear()),ey:safe(()=>x.getEndYear()),sa:safe(()=>x.getStartAge()),ea:safe(()=>x.getEndAge())})),now=new Date().getFullYear(),annual=Array.from({length:10},(_,i)=>{const y=now+i,gz=yearGanzhi(y);return{y,gz,tg:tenGod(d,gz[0])}});return{dy,annual,fy:year,monthly:monthSequence(year,d)}}
function bazi(ec){const p=[ec.getYear(),ec.getMonth(),ec.getDay(),ec.getTime()],hide=[safe(()=>ec.getYearHideGan(),[]),safe(()=>ec.getMonthHideGan(),[]),safe(()=>ec.getDayHideGan(),[]),safe(()=>ec.getTimeHideGan(),[])];return{pillars:p,day:p[2][0],element:STEM_ELEMENT[p[2][0]],ming:safe(()=>ec.getMingGong()),shen:safe(()=>ec.getShenGong()),tai:safe(()=>ec.getTaiYuan()),hide,ss:[safe(()=>ec.getYearShiShenGan()),safe(()=>ec.getMonthShiShenGan()),'日主',safe(()=>ec.getTimeShiShenGan())],nayin:[safe(()=>ec.getYearNaYin()),safe(()=>ec.getMonthNaYin()),safe(()=>ec.getDayNaYin()),safe(()=>ec.getTimeNaYin())]}}
function ziwei(date,h,gender){try{if(!window.iztro?.astro)return null;const c=window.iztro.astro.bySolar(date,timeIndex(h),gender,true,'zh-TW'),o=c.toJSON?c.toJSON():c;return{five:o.fiveElementsClass,soul:o.soul,body:o.body,palaces:(o.palaces||[]).map(p=>({name:p.name,stem:p.heavenlyStem,branch:p.earthlyBranch,body:!!p.isBodyPalace,major:(p.majorStars||[]).map(s=>({name:s.name,b:s.brightness,m:s.mutagen||''})),minor:(p.minorStars||[]).map(s=>s.name)}))}}catch{return null}}
export function currentLuck(t){const y=new Date().getFullYear();return t?.dy?.find(x=>+x.sy<=y&&+x.ey>=y)||null}
export function initChart(){$('flowYear').value=getState().selectedYear;$('calc').addEventListener('click',()=>{try{if(!window.Solar)throw Error('排盤函式庫尚未載入，請重新整理');const date=$('date').value,time=$('time').value||'12:00';if(!date)throw Error('請選擇出生日期');let[y,m,d]=date.split('-').map(Number),[h,mi]=time.split(':').map(Number),solar=Solar.fromYmdHms(y,m,d,h,mi,0),offset=0;if($('trueSolar').checked&&$('lng').value){offset=eot(new Date(y,m-1,d,h,mi))+4*(+$('lng').value-120);const z=new Date(y,m-1,d,h,mi+offset);solar=Solar.fromYmdHms(z.getFullYear(),z.getMonth()+1,z.getDate(),z.getHours(),z.getMinutes(),0)}const lunar=solar.getLunar(),ec=lunar.getEightChar(),bz=bazi(ec),selectedYear=+$('flowYear').value||new Date().getFullYear(),tim=timeline(ec,$('gender').value,selectedYear),zw=ziwei(date,h,$('gender').value);const chart={input:{date,time,gender:$('gender').value,place:$('place').value,longitude:$('lng').value,trueSolar:$('trueSolar').checked},solar:solar.toYmdHms(),lunar:lunar.toString(),offset:+offset.toFixed(1),bazi:bz,ziwei:zw,timelines:tim};setState({chart,selectedYear,selectedPalace:null},{type:'chart-calculated'});persistWorkspace()}catch(e){$('chartOut').textContent=err(e)}});$('refreshTime').addEventListener('click',()=>selectYear(+$('flowYear').value||new Date().getFullYear()))}
export function selectYear(year){const s=getState();if(!s.chart)return;const day=s.chart.bazi.day,chart={...s.chart,timelines:{...s.chart.timelines,fy:year,monthly:monthSequence(year,day)}};setState({chart,selectedYear:year},{type:'year-selected'});persistWorkspace()}
