import {$,esc} from '../core/utils.js';
import {ELEMENTS,TEN_GODS} from '../core/config.js';
import {STEM_ELEMENT,BRANCH_ELEMENT,currentLuck,selectYear} from './chart.js';
import {setState,persistWorkspace} from '../core/store.js';
function add(score,el,val){if(el&&Object.hasOwn(score,el))score[el]+=Number.isFinite(val)?val:0}
function elementScore(b){const score=Object.fromEntries(ELEMENTS.map(x=>[x,0]));b.pillars.forEach(p=>{add(score,STEM_ELEMENT[p[0]],1);add(score,BRANCH_ELEMENT[p[1]],1.15)});(b.hide||[]).flat().forEach(x=>add(score,STEM_ELEMENT[x],.45));return score}
function pctMap(score){const sum=Object.values(score).reduce((a,b)=>a+b,0)||1;return Object.fromEntries(ELEMENTS.map(x=>[x,Math.round(score[x]/sum*100)]))}
function godCounts(b){const c=Object.fromEntries(TEN_GODS.map(x=>[x,0]));(b.ss||[]).filter(x=>x&&x!=='日主').forEach(x=>{if(Object.hasOwn(c,x))c[x]++});return c}
export function initDashboard(){$('years').addEventListener('click',e=>{const card=e.target.closest('[data-year]');if(!card)return;const y=+card.dataset.year;$('flowYear').value=y;selectYear(y)});$('palaces').addEventListener('click',e=>{const card=e.target.closest('[data-palace]');if(!card)return;setState({selectedPalace:card.dataset.palace},{type:'palace-selected'});persistWorkspace()})}
export function renderDashboard(s){if(!s.chart){renderEmpty();return}const{bazi:b,timelines:t,ziwei:z}=s.chart,l=currentLuck(t),score=elementScore(b),pct=pctMap(score),gods=godCounts(b);$('needChart').hidden=true;$('pillars').innerHTML=b.pillars.map((p,i)=>`<article><small>${['年柱','月柱','日柱','時柱'][i]}</small><b>${esc(p)}</b><span>${esc(b.ss[i])}｜藏干 ${esc((b.hide[i]||[]).join('、')||'—')}</span></article>`).join('');$('mDay').textContent=`${b.day} · ${b.element}`;$('mMS').textContent=`${b.ming||'—'} / ${b.shen||'—'}`;$('mZw').textContent=z?.five||'—';$('mLuck').textContent=l?.gz||'待核對';$('sDay').textContent=b.day;$('sLuck').textContent=l?.gz||'—';$('elements').innerHTML=ELEMENTS.map(k=>`<div class="bar" data-element="${k}"><b>${k}</b><i style="--w:${pct[k]}%"></i><span>${pct[k]}%</span></div>`).join('');$('gods').innerHTML=TEN_GODS.map(k=>`<span class="god ${gods[k]?'on':'off'}">${k} × ${gods[k]}</span>`).join('');$('years').innerHTML=t.annual.map(x=>`<div class="yr ${x.y===s.selectedYear?'now':''}" data-year="${x.y}"><small>${x.y}</small><b>${x.gz}</b><em>${x.tg}</em></div>`).join('');$('palaces').innerHTML=z?.palaces?.map(p=>`<div class="palace ${p.name===s.selectedPalace?'selected':''}" data-palace="${esc(p.name)}"><strong>${esc(p.name)}${p.body?' · 身宮':''}</strong><span>${esc(p.major.map(st=>st.name+(st.m?'·化'+st.m:'')).join('、')||'空宮')}<br>${esc((p.stem||'')+(p.branch||''))}</span></div>`).join('')||'紫微函式庫尚未載入';const selected=t.annual.find(x=>x.y===s.selectedYear),pal=z?.palaces?.find(p=>p.name===s.selectedPalace);$('insight').textContent=buildInsight(b,l,selected,pal,z);$('chartOut').textContent=`四柱：${b.pillars.join('　')}\n日主：${b.day}（${b.element}）\n命宮：${b.ming||'—'}　身宮：${b.shen||'—'}　胎元：${b.tai||'—'}\n藏干：${b.hide.map(x=>x.join('、')).join(' / ')}\n納音：${b.nayin.join(' / ')}\n真太陽時偏移：約 ${s.chart.offset} 分鐘\n紫微五行局：${z?.five||'—'}　命主：${z?.soul||'—'}　身主：${z?.body||'—'}`;$('timeOut').textContent='【大運】\n'+t.dy.map(x=>`${x.gz}｜${x.sy}–${x.ey}｜${x.sa}–${x.ea}歲`).join('\n')+'\n\n【未來十年】\n'+t.annual.map(x=>`${x.y} ${x.gz}（${x.tg}）`).join('　')+`\n\n【${t.fy} 十二流月】\n`+t.monthly.map(x=>`${x.n}. ${x.gz}（${x.tg}）`).join('　');$('flowYear').value=s.selectedYear}
function buildInsight(b,l,selected,pal,z){let text=`日主為${b.day}（${b.element}），當前大運${l?.gz||'待核對'}。`;if(selected)text+=`目前選中 ${selected.y} ${selected.gz}（${selected.tg}），十二流月已同步切換。`;if(pal)text+=`紫微目前聚焦「${pal.name}」，主星：${pal.major.map(x=>x.name).join('、')||'空宮'}。`;else text+=`紫微命宮：${z?.palaces?.find(x=>x.name==='命宮')?.major?.map(x=>x.name).join('、')||'待核對'}。`;return text+' 所有 AI 詳批會使用當前選中的年份與完整命盤狀態。'}
function renderEmpty(){$('elements').innerHTML=ELEMENTS.map(k=>`<div class="bar" data-element="${k}"><b>${k}</b><i style="--w:0%"></i><span>0%</span></div>`).join('');$('gods').innerHTML=TEN_GODS.map(k=>`<span class="god off">${k} × 0</span>`).join('')}
