import {SUPABASE_URL,SUPABASE_KEY} from '../core/config.js';
import {$,err,esc} from '../core/utils.js';
import {getState,setState,persistWorkspace} from '../core/store.js';
import {ensureAuth} from './auth.js';
import {go} from '../core/router.js';
const headers=token=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',Authorization:'Bearer '+token});
export function initHistory(){$('save').addEventListener('click',saveHistory);$('historyRefresh').addEventListener('click',loadHistory);$('history').addEventListener('click',e=>{const b=e.target.closest('[data-history]');if(b)restoreHistory(b.dataset.history)})}
export async function saveHistory(){const s=getState();if(!s.report){$('progressText').textContent='尚無可儲存報告';return}if(!await ensureAuth())return;try{const r=await fetch(SUPABASE_URL+'/rest/v1/xj_analyses',{method:'POST',headers:{...headers(getState().auth.session.access_token),Prefer:'return=minimal'},body:JSON.stringify({user_id:getState().auth.user.id,title:'玄鑑詳批 · '+(s.chart?.input?.date||new Date().toLocaleDateString('zh-TW')),data_json:{chart:s.chart,selectedYear:s.selectedYear,selectedPalace:s.selectedPalace,visual:s.visual},report:'',ai_report:s.report})});if(!r.ok)throw Error(err(await r.json().catch(()=>({}))));$('progressText').textContent='已儲存至歷史';loadHistory()}catch(e){$('progressText').textContent='儲存失敗：'+err(e)}}
export async function loadHistory(){if(!getState().auth.user)return;try{const r=await fetch(SUPABASE_URL+'/rest/v1/xj_analyses?select=id,title,data_json,ai_report,created_at&order=created_at.desc&limit=30',{headers:headers(getState().auth.session.access_token)}),j=await r.json();if(!r.ok)throw Error(err(j));setState({history:Array.isArray(j)?j:[]},{type:'history'});renderHistory(getState())}catch(e){$('history').textContent='讀取失敗：'+err(e)}}
function renderHistory(s){$('history').innerHTML=s.history.length?'':'尚無歷史分析';s.history.forEach(x=>$('history').insertAdjacentHTML('beforeend',`<button data-history="${esc(x.id)}">${esc(x.title)} · ${new Date(x.created_at).toLocaleString('zh-TW')}</button>`))}
function restoreHistory(id){const row=getState().history.find(x=>x.id===id);if(!row)return;const d=row.data_json||{},report=row.ai_report||'';setState({chart:d.chart||null,selectedYear:d.selectedYear||d.chart?.timelines?.fy||new Date().getFullYear(),selectedPalace:d.selectedPalace||null,visual:d.visual||null,report,reportParts:report?report.split(/(?=^#\s+)/m).filter(Boolean):[],reportStatus:{running:false,completed:(report.match(/^#\s+/gm)||[]).length,total:5,current:'',chars:report.length,sections:(report.match(/^#\s+/gm)||[]).length}},{type:'history-restore'});persistWorkspace();go('report')}
export {renderHistory};
